services:
  db:
    image: annalevina/mysql-bookstore:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    networks:
      - bookstore-network

  api:
    image: annalevina/bookstore-api:latest
    environment:
      DATABASE_URL: "mysql://user:123@db:3306/bookstore"
    depends_on:
      - db
    ports:
      - "8002:8000"
    networks:
      - bookstore-network

  web:
    build: .
    environment:
      API_DOMAIN: "http://api:8002"
      DEBUG: "True"
    ports:
      - "8001:8000"
    networks:
      - bookstore-network
    volumes:
      - .:/Bookstore
    depends_on:
      - api

networks:
  bookstore-network:
    driver: bridge
